#!/bin/bash

>.env

echo "Generating .env file..."

echo "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}" >>.env
echo "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}" >>.env
echo "SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}" >>.env
echo "POSTGRES_DB=${POSTGRES_DB}" >>.env
echo "POSTGRES_USER=${POSTGRES_USER}" >>.env
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >>.env
echo "POSTGRES_HOST=${POSTGRES_HOST}" >>.env
echo "POSTGRES_PORT=${POSTGRES_PORT}" >>.env

echo "AIRFLOW_UID=${AIRFLOW_UID}" >>.env
echo "AIRFLOW_DB_NAME=${AIRFLOW_DB_NAME}" >>.env
echo "AIRFLOW_ADMIN_USER=${AIRFLOW_ADMIN_USER}" >>.env
echo "AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}" >>.env
echo "AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}" >>.env
echo "AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME}" >>.env
echo "AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME}" >>.env

echo "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}" >>.env
echo "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}" >>.env
echo "MY_SPOTIFY_USERNAME=${MY_SPOTIFY_USERNAME}" >>.env
echo "MY_SPOTIFY_PASSWORD=${MY_SPOTIFY_PASSWORD}" >>.env
echo "MB_DB_DBNAME=${MB_DB_DBNAME}" >>.env
