import os

from dotenv import load_dotenv

load_dotenv()


SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_CODE = os.getenv("CODE")
SPOTIFY_ACCESS_TOKEN = os.getenv("SPOTIFY_ACCESS_TOKEN")
SPOTIFY_AUTHORIZATION_CODE = os.getenv("SPOTIFY_AUTHORIZATION_CODE")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")
MY_SPOTIFY_USERNAME = os.getenv("MY_SPOTIFY_USERNAME")
MY_SPOTIFY_PASSWORD = os.getenv("MY_SPOTIFY_PASSWORD")

# Database
DB_NAME = os.getenv("POSTGRES_DB")
DB_USER = os.getenv("POSTGRES_USER")
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DB_HOST = os.getenv("POSTGRES_HOST")
DB_PORT = int(os.getenv("POSTGRES_PORT"))
